---
apiVersion: v1
kind: Service
metadata:
  name: oam-crd-conversion
  labels:
    oam: crd-conversion
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    oam: crd-conversion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oam-crd-conversion
  labels:
    oam: crd-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      oam: crd-conversion
  template:
    metadata:
      name: oam-crd-conversion
      labels:
        oam: crd-conversion
    spec:
      containers:
        - image: example:v0.4
          name: convert
          volumeMounts:
            - name: ca
              mountPath: "/etc/webhook/cert"
              readOnly: true
      volumes:
        - name: ca
          secret:
            secretName: webhook-server-cert
