apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.core.oam.dev
spec:
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            hostPort:
              type: string
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            host:
              type: string
            port:
              type: string
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1alpha1","v1alpha2","v1beta1"]
      clientConfig:
        service:
          namespace: default
          name: oam-crd-conversion
          path: /exampleconvert
        caBundle: ${CA_BUNDLE}